import Head from "next/head";
import relImage from "../../public/K.png";

export default function Home({ theme }) {
  return (
    <>
      <Head>
        <title>kristof</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href={relImage.src} />
      </Head>
      <main className={`index-main ${theme}`}>
        <div className="welcomer">
          {theme === "dark" ? (
            <h1 className="darkh1">Kristof’s Journal</h1>
          ) : (
            <h1>Kristof’s Journal</h1>
          )}
          <hr className={theme === "light" ? "divider" : "dark-divider"} />
          <p>
            My ideas and thoughts about web development, programming and self
            improvement
          </p>
        </div>
      </main>
    </>
  );
}
